# Generated by Django 5.0.5 on 2024-07-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_homework_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='user',
        ),
    ]
